# Backbone配置
backbone:
  out_channels: 256  # 特征提取器输出通道数
  init_conv:
    in_channels: 1
    out_channels: 64
    kernel_size: 7
    stride: 2
  multi_scale:
    in_channels: 64
    out_channels: 64
  layer1:
    in_channels: 64
    out_channels: 128
  layer2:
    in_channels: 128
    out_channels: 256

# 检测头配置
detector:
  in_channels: 256
  num_classes: 1
  num_anchors: 1
  fpn:
    in_channels: 256
    fpn_channels: 128

# 时序模块配置
temporal:
  in_channels: 256
  num_heads: 8
  num_layers: 2
  dropout: 0.1
  positional_encoding:
    d_model: 256
    max_len: 500

